services:
  - type: web
    name: house-of-bounce
    runtime: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    plan: free
    envVars:
      - key: PORT
        generateValue: false
